id: Lisp
namespace: OffByOneStudios
name: Speech Problems
version: "1.0.0"
repo: http://github.com/OffByOneStudios/craft-lisp
dependencies:
  - Util
  - Types
  
vendor-dependencies:
  x86_64-pc-windows-msvccoff:
    - "zmq"
    - "LLVMX86Info"
    - "LLVMX86Utils"
    - "LLVMXRay"
    - "LLVMAnalysis"
    - "LLVMAsmParser"
    - "LLVMAsmPrinter"
    - "LLVMBinaryFormat"
    - "LLVMBitReader"
    - "LLVMBitWriter"
    - "LLVMCodeGen"
    - "LLVMCore"
    - "LLVMCoroutines"
    - "LLVMCoverage"
    - "LLVMDebugInfoCodeView"
    - "LLVMDebugInfoDWARF"
    - "LLVMDebugInfoMSF"
    - "LLVMDebugInfoPDB"
    - "LLVMDemangle"
    - "LLVMDlltoolDriver"
    - "LLVMExecutionEngine"
    - "LLVMGlobalISel"
    - "LLVMInstCombine"
    - "LLVMInstrumentation"
    - "LLVMInterpreter"
    - "LLVMipo"
    - "LLVMIRReader"
    - "LLVMLibDriver"
    - "LLVMLineEditor"
    - "LLVMLinker"
    - "LLVMLTO"
    - "LLVMMC"
    - "LLVMMCDisassembler"
    - "LLVMMCJIT"
    - "LLVMMCParser"
    - "LLVMMIRParser"
    - "LLVMObjCARCOpts"
    - "LLVMObject"
    - "LLVMObjectYAML"
    - "LLVMOption"
    - "LLVMOrcJIT"
    - "LLVMPasses"
    - "LLVMProfileData"
    - "LLVMRuntimeDyld"
    - "LLVMScalarOpts"
    - "LLVMSelectionDAG"
    - "LLVMSupport"
    - "LLVMSymbolize"
    - "LLVMTableGen"
    - "LLVMTarget"
    - "LLVMTestingSupport"
    - "LLVMTransformUtils"
    - "LLVMVectorize"
    - "LLVMX86AsmParser"
    - "LLVMX86AsmPrinter"
    - "LLVMX86CodeGen"
    - "LLVMX86Desc"
    - "LLVMX86Disassembler"
  osx_x64_clang:
    - "zmq"
  debian_x64_gcc:
    - "zmq"

platform-dependencies:
  x86_64-pc-windows-msvccoff: []
  osx_x64_clang: []
  debian_x64_gcc: []
  
platform-flags:
  x86_64-pc-windows-msvccoff: []
  osx_x64_clang: 
    - "-std=c++1z"
    - "-stdlib=libc++"
    - "-Wc++11-extensions"
  debian_x64_gcc: 
    - "-std=gnu++1z"
    - "-pthread"
    - "-fpermissive"
  
platform-link-flags:
  x86_64-pc-windows-msvccoff:
    - "/ignore:4099"

files:
  library:
    - src/**/*.*
  test:
    - test/**/*.*
  entry:
    - entry/**/*.*
