id: CraftEngine.Deps.Lisp
name: Speech Problems
version: "1.0.0"
repo: http://github.com/OffByOneStudios/craft-lisp
dependencies:
  - CraftEngine.Deps.Util
  - CraftEngine.Deps.Types
  
vendor-dependencies:
  win_x64_vc140: []
  osx_x64_clang: []
  debian_x64_gcc: []

platform-dependencies:
  win_x64_vc140: []
  osx_x64_clang: []
  debian_x64_gcc: []
  
platform-flags:
  win_x64_vc140: []
  osx_x64_clang: 
    - "-std=c++1z"
    - "-stdlib=libc++"
    - "-Wc++11-extensions"
  debian_x64_gcc: 
    - "-std=gnu++1z"
    - "-pthread"
    - "-fpermissive"
  

files:
  library:
    - src/**/*.*
  test:
    - test/**/*.*
  entry:
    - entry/**/*.*
